version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: spb_user
      POSTGRES_PASSWORD: spb_pass
      POSTGRES_DB: spb_history
    ports:
      - "5432:5432"
    volumes:
      - spbdata:/var/lib/postgresql/data

volumes:
  spbdata:
